version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: traslado_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - huella_network

networks:
  huella_network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  # postgres-db:
  #   image: postgres:15.3
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: my-db
  #     POSTGRES_PASSWORD: 123456
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
